<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class PostFacade extends Facade
{


    protected static function getFacadeAccessor(): string
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'postMAxMindServices';
    }
}
